global:
  scrape_interval:     60s
  evaluation_interval: 60s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
  - dns_sd_configs:
    - names: 
      - 'tasks.alertmanager'
      type: A
      port: 9093

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'alertmanager'
    dns_sd_configs:
    - names:
      - 'tasks.alertmanager'
      type: 'A'
      port: 9093

  - job_name: 'remote_agent'
    dns_sd_configs:
    - names:
      - 'tasks.remote_agent'
      type: 'A'
      port: 9126
